// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/didikz/goshu/views/components"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Head().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<body class=\"bg-gray-900 text-gray-100 min-h-screen flex flex-col\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Header().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<main class=\"flex-grow container mx-auto px-4 py-8\"><div class=\"max-w-2xl mx-auto text-center\"><h2 class=\"text-4xl font-bold mb-4\">Shorten Your URLs</h2><p class=\"text-xl mb-8\">Create concise, shareable links in seconds.</p><form class=\"mb-8\" action=\"/shorten\" hx-post=\"/shorten\" hx-trigger=\"submit\" hx-target=\"#shorten-url\" enctype=\"application/x-www-form-urlencoded\"><div class=\"flex\"><input type=\"url\" name=\"url\" id=\"url\" placeholder=\"https://your-long-url-here.com\" class=\"flex-grow p-3 rounded-l-lg bg-gray-700 focus:outline-none focus:ring-2 focus:ring-blue-500\"> <button type=\"submit\" id=\"submit\" class=\"bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-6 rounded-r-lg transition duration-300\">Shorten</button></div></form><div class=\"py-3 px-6 mb-4 rounded-r-md bg-blue-600 text-white\" id=\"shorten-url\"></div><div class=\"grid grid-cols-1 md:grid-cols-3 gap-8\"><div class=\"bg-gray-800 p-6 rounded-lg\"><h3 class=\"text-xl font-semibold mb-2\">Fast</h3><p>Generate short links in an instant.</p></div><div class=\"bg-gray-800 p-6 rounded-lg\"><h3 class=\"text-xl font-semibold mb-2\">Reliable</h3><p>Your links will always redirect correctly.</p></div><div class=\"bg-gray-800 p-6 rounded-lg\"><h3 class=\"text-xl font-semibold mb-2\">Secure</h3><p>We prioritize the safety of your data.</p></div></div></div></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Footer().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script>\n            document.body.addEventListener('htmx:afterOnLoad', function(event) {\n            if (event.detail.elt.id === 'shorten-url') {\n                var jsonResponse = JSON.parse(event.detail.xhr.responseText);\n                var url = jsonResponse.url;\n                \n                // Now you can use the URL as needed, for example:\n                event.detail.elt.innerHTML = '<a href=\"' + url + '\">' + url + '</a>';\n            }\n        });\n        </script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
